# Generated by Django 3.1.1 on 2023-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('blockchain', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('token_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
