# Generated by Django 3.1.1 on 2023-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20230419_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptos', models.CharField(max_length=200)),
                ('exchanges', models.CharField(max_length=200)),
                ('marketcap', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('dominance', models.CharField(max_length=200)),
                ('ethgas', models.CharField(max_length=200)),
            ],
        ),
    ]
