# Generated by Django 3.1.1 on 2023-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbitrageDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('diff', models.CharField(max_length=200)),
                ('blockchain', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('exchangeName_low', models.CharField(max_length=200)),
                ('exchangeName_high', models.CharField(max_length=200)),
                ('marketpair_low', models.CharField(max_length=200)),
                ('marketpair_high', models.CharField(max_length=200)),
                ('price_low', models.CharField(max_length=200)),
                ('price_high', models.CharField(max_length=200)),
                ('volumeusd_low', models.CharField(max_length=200)),
                ('volumeusd_high', models.CharField(max_length=200)),
                ('liquidy_score_low', models.CharField(max_length=200)),
                ('liquidy_score_high', models.CharField(max_length=200)),
                ('audit', models.CharField(max_length=200)),
                ('dextoolslink', models.CharField(max_length=200)),
                ('tokensnifferlink', models.CharField(max_length=200)),
                ('img_path', models.CharField(max_length=200)),
                ('exchangeName_low_link', models.CharField(max_length=200)),
                ('exchangeName_high_link', models.CharField(max_length=200)),
            ],
        ),
    ]
