# Generated by Django 3.1.1 on 2023-04-20 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arbitragedeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abitragedeals',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abitragedeals',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
